### ISSUE TITLE
Error in download 

### ISSUE THREAD

**Issue by Casshernsins** [acgtools/hanime-hunter#40]
### Describe the bug

hani dl https://hanime.tv/videos/hentai/bikyaku-seido-kaichou-ai
INFO Site: hanime.tv
INFO Anime found: Bikyaku Seido Kaichou Ai, Searching episodes, Please wait a moment...
INFO Episodes found: [`bikyaku-seido-kaichou-ai`]
INFO Start downloading ...

Press ctrl+c to quit

Caught panic:

runtime error: invalid memory address or nil pointer dereference

Restoring terminal...

goroutine 1 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.21.7/x64/src/runtime/debug/stack.go:24 +0x5e
runtime/debug.PrintStack()
        /opt/hostedtoolcache/go/1.21.7/x64/src/runtime/debug/stack.go:16 +0x13
github.com/charmbracelet/bubbletea.(*Program).Run.func1()
        /home/runner/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.24.2/tea.go:440 +0x91
panic({0xaf02a0?, 0xf53c90?})
        /opt/hostedtoolcache/go/1.21.7/x64/src/runtime/panic.go:920 +0x270
github.com/acgtools/hanime-hunter/internal/tui/progressbar.(*Model).Update(0xc0000a8700, {0xb2c020?, 0xc0001e6f90?})
        /home/runner/work/hanime-hunter/hanime-hunter/internal/tui/progressbar/update.go:58 +0x165
github.com/charmbracelet/bubbletea.(*Program).eventLoop(0xc0001e80c0, {0xc3df90?, 0xc0000a8700?}, 0xc00007d958?)
        /home/runner/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.24.2/tea.go:373 +0x637
github.com/charmbracelet/bubbletea.(*Program).Run(0xc0001e80c0)
        /home/runner/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.24.2/tea.go:503 +0x85c
github.com/acgtools/hanime-hunter/cmd.download({0xc00001e140, 0x38}, 0xc00009e078)
        /home/runner/work/hanime-hunter/hanime-hunter/cmd/download.go:99 +0x450
github.com/acgtools/hanime-hunter/cmd.glob..func1(0xc000174200?, {0xc00008e0b0, 0x1, 0xb65d68?})
        /home/runner/work/hanime-hunter/hanime-hunter/cmd/download.go:40 +0xc5
github.com/spf13/cobra.(*Command).execute(0xf68000, {0xc00008e080, 0x1, 0x1})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:983 +0xabc
github.com/spf13/cobra.(*Command).ExecuteC(0xf682e0)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/acgtools/hanime-hunter/cmd.Execute()
        /home/runner/work/hanime-hunter/hanime-hunter/cmd/root.go:19 +0x28
main.main()
        /home/runner/work/hanime-hunter/hanime-hunter/main.go:6 +0xf

### How To Reproduce

Just download anything.

```
 - Platform:   <!-- e.g. windows 11-->
 - Version:    <!-- - v0.3.2 -->

### Additional context (Optional) 
<!-- Add any other context about the problem here. -->
Already changed chcp to 65001

**Comment by ImPeekaboo** [comment]
Maybe the terminal not support bubbletea progress bar. Please add options to non active progress bar or options to make progress bar more simple 🙏🏼.

**Comment by Mathisdifficult** [comment]
same as you
